[package]
name = "mack"
version = "0.1.0"
authors = ["Chris Down <chris@chrisdown.name>"]

[dependencies]
clap = "*"
failure = "*"
taglib = { git = "https://github.com/ebassi/taglib-rust", rev = "513dabf1c56c"}
ignore = "*"
